<?php

namespace Tests\Unit\App\Models;

use App\Models\PaymentSum;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PaymentSumTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        // DB接続先がテスト用に切り替わっているか確認
        // dd(env('APP_ENV'), env('DB_DATABASE'), env('DB_CONNECTION'));
    }

    /**
     * @test
     */
    public function register_レコードがなければcreateされること()
    {
        self::assertSame(0, count(PaymentSum::all())); // register実行前のPaymentSumsテーブルの件数検証
        PaymentSum::register('2021', '12', '1', '65000');
        self::assertSame(1, count(PaymentSum::all())); // register実行後のPaymentSumsテーブルの件数検証
    }

    /**
     * @test
     */
    public function register_同じデータの登録をした場合重複して登録されないこと()
    {
        // 1回目の実行
        PaymentSum::register('2021', '12', '1', '65000');
        self::assertSame(1, count(PaymentSum::all()));

        // 2回目の実行
        PaymentSum::register('2021', '12', '1', '65000');
        self::assertSame(1, count(PaymentSum::all()));
    }

    /**
     * @test
     */
    public function register_同じデータの登録をした場合updated_atの値は上書きされないこと()
    {
        // 1回目の実行
        PaymentSum::register('2021', '12', '1', '65000');
        $firstResult = PaymentSum::first();
        $firstCreatedAt = (new Carbon($firstResult->created_at))->toDateTimeString();
        $firstUpdatedAt = (new Carbon($firstResult->updated_at))->toDateTimeString();

        // 2回目の実行
        PaymentSum::register('2021', '12', '1', '65000');
        $secondResult = PaymentSum::first();

        self::assertSame($firstCreatedAt, (new Carbon($secondResult->created_at))->toDateTimeString());
        self::assertSame($firstUpdatedAt, (new Carbon($secondResult->updated_at))->toDateTimeString());
    }

    /**
     * @test
     */
    public function register_別の年データの登録をした場合別のレコードとしてcreateされること()
    {
        // 1回目の実行
        PaymentSum::register('2021', '12', '1', '65000');
        // 2回目の実行
        PaymentSum::register('2020', '12', '1', '65000');

        self::assertSame(2, count(PaymentSum::all()));
    }

    /**
     * @test
     */
    public function register_別の月データの登録をした場合別のレコードとしてcreateされること()
    {
        // 1回目の実行
        PaymentSum::register('2021', '12', '1', '65000');
        // 2回目の実行
        PaymentSum::register('2021', '11', '1', '65000');

        self::assertSame(2, count(PaymentSum::all()));
    }

    /**
     * @test
     */
    public function register_別のユーザーIDデータの登録をした場合別のレコードとしてcreateされること()
    {
        // 1回目の実行
        PaymentSum::register('2021', '12', '1', '65000');
        // 2回目の実行
        PaymentSum::register('2021', '12', '2', '65000');

        self::assertSame(2, count(PaymentSum::all()));
    }
}
