version: '3'

services:
  php:
    build: ./php
    volumes:
      - ../:/var/www

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_project
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

#  node.jsはPHPコンテナ内にインストールするようにしたため下記をコメントします。
#  node:
#    image: node:12.13-alpine
#    tty: true
#    volumes:
#      - ./src:/var/www
#    working_dir: /var/www
